### ISSUE TITLE
`X11docker` will defeat the image copy and paste from shutter/ksnip onto GitHub. [--clipboard]

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#428]
On Ubuntu 20.04.3 LTS, I'm using the git master version of `x11docker` to run [Deepin wine docker image](https://github.com/hongyi-zhao/dockerfile/blob/master/deepin/wine/Dockerfile) with the command described [here](https://github.com/hongyi-zhao/dockerfile#run-the-image-using-x11docker):

```shell
# x11docker version:
$ git log -1
commit 6f2bd38b71f5ba6e928c6381b529e6ff7bbcec0b (HEAD -> master, origin/master, origin/HEAD)
Author: mviereck <bachbaum24@gmx.de>
Date:   Sat Apr 2 11:23:14 2022 +0200

    --clipboard: do not echo script

$ x11docker --runasroot 'sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers
        |#$ sudo grep -Ev '\''^[ ]*(#|$)'\'' /etc/sudoers  
        |Defaultsenv_reset
        |Defaultsmail_badpass
        |Defaultssecure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
        |rootlesskitALL=(ALL:ALL) ALL
        |%admin ALL=(ALL) ALL
        |%sudoALL=(ALL:ALL) ALL
        |$USER ALL=(ALL) NOPASSWD:ALL
EOF' --xephyr --network=bridge --pulseaudio --xoverip --home --share=$HOME --sudouser -c --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot
```
See the screenshot below:
![Selection_089](https://user-images.githubusercontent.com/11155854/161407971-ee6fd8c8-5d1e-4f4d-b456-578f82417bb4.png)

At the same time, I use [shutter](https://github.com/shutter-project/shutter) and [ksnip](https://github.com/ksnip/ksnip) as my screenshot tools. Today, I find a strange thing: After I start the docker image with `x11docker` as mentioned above, the screenshot captured by [shutter](https://github.com/shutter-project/shutter) and [ksnip](https://github.com/ksnip/ksnip) will not be able to copy and paste directly from inside them onto GitHub. If I close `x11docker`, this problem disappears.

Any hints for fixing this problem?

Regards,
HZ

**Comment by mviereck** [comment]
There is an issue with the `-c, --clipboard` option. The clipboard script cannot handle picture clips.
Please try without `-c`, or use `--nxagent` instead of `--xephyr` because `nxagent` has its own clipboard management.

**Comment by hongyi-zhao** [comment]
Which one is more powerful and feature-rich?

**Comment by mviereck** [comment]
> However, this disables the ability to copy and paste text content between the host and the docker container, which is a feature I also want.

With `--nxagent` and `--xpra` you can use `-c`. Both have their own clipboard management. With `--xephyr` x11docker uses a custom script.

> Then I use the following option of x11docker:

> -c --xpra

> But the Deepin desktop doesn't appear at all, and I only see the following log on stdout:

I could reproduce here. I'll look at this.

**Comment by hongyi-zhao** [comment]
> With `--nxagent` and `--xpra` you can use `-c`. Both have their own clipboard management. 

I tried `-c --nxagent`, but it still will defeat the image copy and paste from shutter/ksnip onto GitHub.

> With `--xephyr` x11docker uses a custom script.

What's the script and how to use it?

**Comment by mviereck** [comment]
> I tried -c --nxagent, but it still will defeat the image copy and paste from shutter/ksnip onto GitHub.

Do you have another x11docker instance running with `--xephyr --clipboard`? That might disturb the clipboard.

>  Edit: --xpra fails along with --xoverip. Without this it works.

Is fixed now.

> What's the script and how to use it?

x11docker generates it internally.
Depending on the display numbers etc. it looks like this:
```
#! /usr/bin/env bash
# share clipboard between X servers :0 and 192.168.10.100:112

mysleep () 
{ 
    sleep "${1:-1}" 2> /dev/null || sleep 1
}
rocknroll () 
{ 
    [ -s "$Timetosaygoodbyefile" ] && return 1;
    [ -e "$Timetosaygoodbyefile" ] || return 1;
    return 0
}
Timetosaygoodbyefile='/home/werner/.cache/x11docker/87037275931-deepin-wine-apricot/share/timetosaygoodbye'

while rocknroll ; do
  # read content of clipboard of first X server :0
  X1clip="$(env DISPLAY=:0 XAUTHORITY=/home/werner/.cache/x11docker/87037275931-deepin-wine-apricot/Xauthority.host.0 xclip -selection clipboard -out)"

  # check if clipboard of first X server has changed; if yes, send new content to second X server
  [ "$Shareclip" != "$X1clip" ] && {
    Shareclip="$X1clip"
    env DISPLAY=192.168.10.100:112 XAUTHORITY=/home/werner/.cache/x11docker/87037275931-deepin-wine-apricot/share/Xauthority.client xclip -selection clipboard -in <<<  "$Shareclip"
#    echo "$Shareclip" | env DISPLAY=192.168.10.100:112 XAUTHORITY=/home/werner/.cache/x11docker/87037275931-deepin-wine-apricot/share/Xauthority.client xclip -selection clipboard -in
  }
  Shareclip="${Shareclip:-' '}"     # avoid empty string error
  mysleep 0.3                       # sleep a bit to avoid high cpu usage

  # read content of clipboard of second X server 192.168.10.100:112
  X2clip="$(env DISPLAY=192.168.10.100:112 XAUTHORITY=/home/werner/.cache/x11docker/87037275931-deepin-wine-apricot/share/Xauthority.client xclip -selection clipboard -out)"

  # check if clipboard of second X server has changed; if yes, send new content to first X server
  [ "$Shareclip" != "$X2clip" ] && {
    Shareclip="$X2clip"
    env DISPLAY=:0 XAUTHORITY=/home/werner/.cache/x11docker/87037275931-deepin-wine-apricot/Xauthority.host.0 xclip -selection clipboard -in <<<  "$Shareclip"
#    echo "$Shareclip" | env DISPLAY=:0 XAUTHORITY=/home/werner/.cache/x11docker/87037275931-deepin-wine-apricot/Xauthority.host.0 xclip -selection clipboard -in
  }
  Shareclip="${Shareclip:-' '}"     # avoid empty string error
  mysleep 0.3                       # sleep a bit to avoid high cpu usage
done
```

**Comment by hongyi-zhao** [comment]
> > I tried -c --nxagent, but it still will defeat the image copy and paste from shutter/ksnip onto GitHub.
> 
> Do you have another x11docker instance running with `--xephyr --clipboard`? That might disturb the clipboard.

See the following running processes when I'm using `-c --nxagent`:

```shell
werner@X10DAi-00:~$ pgrep -af 'x11docker'
945029 xargs -I{} -r x11docker --runasroot sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers         |#$ sudo grep -Ev '^[ ]*(#|$)' /etc/sudoers           |Defaultsenv_reset         |Defaults	mail_badpass         |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"         |root	ALL=(ALL:ALL) ALL         |%admin ALL=(ALL) ALL         |%sudo	ALL=(ALL:ALL) ALL         |$USER ALL=(ALL) NOPASSWD:ALL 	EOF -c --nxagent --network=bridge --pulseaudio --xoverip --home --share=/home/werner --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- {}
945122 bash /home/werner/Public/repo/github.com/mviereck/x11docker.git/x11docker --runasroot sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers         |#$ sudo grep -Ev '^[ ]*(#|$)' /etc/sudoers           |Defaults	env_reset         |Defaults	mail_badpass         |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"         |root	ALL=(ALL:ALL) ALL         |%admin ALL=(ALL) ALL         |%sudo	ALL=(ALL:ALL) ALL         |$USER ALL=(ALL) NOPASSWD:ALL 	EOF -c --nxagent --network=bridge --pulseaudio --xoverip --home --share=/home/werner --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot
947991 bash /home/werner/Public/repo/github.com/mviereck/x11docker.git/x11docker --runasroot sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers         |#$ sudo grep -Ev '^[ ]*(#|$)' /etc/sudoers           |Defaults	env_reset         |Defaults	mail_badpass         |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"         |root	ALL=(ALL:ALL) ALL         |%admin ALL=(ALL) ALL         |%sudo	ALL=(ALL:ALL) ALL         |$USER ALL=(ALL) NOPASSWD:ALL 	EOF -c --nxagent --network=bridge --pulseaudio --xoverip --home --share=/home/werner --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot
947995 tail --pid=945122 --retry -n +1 -F /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/stderr /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/stdout /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/compositor.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/container.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/systemd.journal.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/message.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/xinit.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/xpra.client.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/xpra.server.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/stderr /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/stdout /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/compositor.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/container.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/systemd.journal.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/message.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/xinit.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/xpra.client.log /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/xpra.server.log
947996 bash /home/werner/Public/repo/github.com/mviereck/x11docker.git/x11docker --runasroot sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers         |#$ sudo grep -Ev '^[ ]*(#|$)' /etc/sudoers           |Defaults	env_reset         |Defaults	mail_badpass         |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"         |root	ALL=(ALL:ALL) ALL         |%admin ALL=(ALL) ALL         |%sudo	ALL=(ALL:ALL) ALL         |$USER ALL=(ALL) NOPASSWD:ALL 	EOF -c --nxagent --network=bridge --pulseaudio --xoverip --home --share=/home/werner --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot
947997 bash /home/werner/Public/repo/github.com/mviereck/x11docker.git/x11docker --runasroot sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers         |#$ sudo grep -Ev '^[ ]*(#|$)' /etc/sudoers           |Defaults	env_reset         |Defaults	mail_badpass         |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"         |root	ALL=(ALL:ALL) ALL         |%admin ALL=(ALL) ALL         |%sudo	ALL=(ALL:ALL) ALL         |$USER ALL=(ALL) NOPASSWD:ALL 	EOF -c --nxagent --network=bridge --pulseaudio --xoverip --home --share=/home/werner --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot
948775 bash /home/werner/Public/repo/github.com/mviereck/x11docker.git/x11docker --runasroot sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers         |#$ sudo grep -Ev '^[ ]*(#|$)' /etc/sudoers           |Defaults	env_reset         |Defaults	mail_badpass         |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"         |root	ALL=(ALL:ALL) ALL         |%admin ALL=(ALL) ALL         |%sudo	ALL=(ALL:ALL) ALL         |$USER ALL=(ALL) NOPASSWD:ALL 	EOF -c --nxagent --network=bridge --pulseaudio --xoverip --home --share=/home/werner --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot
948842 bash /home/werner/Public/repo/github.com/mviereck/x11docker.git/x11docker --runasroot sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers         |#$ sudo grep -Ev '^[ ]*(#|$)' /etc/sudoers           |Defaults	env_reset         |Defaults	mail_badpass         |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"         |root	ALL=(ALL:ALL) ALL         |%admin ALL=(ALL) ALL         |%sudo	ALL=(ALL:ALL) ALL         |$USER ALL=(ALL) NOPASSWD:ALL 	EOF -c --nxagent --network=bridge --pulseaudio --xoverip --home --share=/home/werner --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot
953019 xinit /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/xinitrc -- /usr/bin/Xephyr :119 -retro +extension RANDR +extension RENDER +extension GLX +extension XVideo +extension DOUBLE-BUFFER +extension SECURITY +extension DAMAGE +extension X-Resource -extension XINERAMA -xinerama -extension MIT-SHM +extension Composite +extension COMPOSITE -extension XTEST -tst -dpms -s off -auth /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/Xauthority.server -listen tcp -dpi 96 -resizeable -noxv -screen 1824x984
953020 /usr/bin/Xephyr :119 -retro +extension RANDR +extension RENDER +extension GLX +extension XVideo +extension DOUBLE-BUFFER +extension SECURITY +extension DAMAGE +extension X-Resource -extension XINERAMA -xinerama -extension MIT-SHM +extension Composite +extension COMPOSITE -extension XTEST -tst -dpms -s off -auth /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/Xauthority.server -listen tcp -dpi 96 -resizeable -noxv -screen 1824x984
953059 sh /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/xinitrc
953147 bash /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/clipboardrc
953224 bash /home/werner/Public/repo/github.com/mviereck/x11docker.git/x11docker --runasroot sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers         |#$ sudo grep -Ev '^[ ]*(#|$)' /etc/sudoers           |Defaults	env_reset         |Defaults	mail_badpass         |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"         |root	ALL=(ALL:ALL) ALL         |%admin ALL=(ALL) ALL         |%sudo	ALL=(ALL:ALL) ALL         |$USER ALL=(ALL) NOPASSWD:ALL 	EOF -c --nxagent --network=bridge --pulseaudio --xoverip --home --share=/home/werner --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot
953227 /usr/bin/docker run --pull never --rm --tty --name x11docker_X119_hongyizhao-deepin-wine-apricot_89975920014 --user root --userns=host --runtime=runc --network bridge --cap-drop ALL --cap-add AUDIT_WRITE --cap-add CHOWN --cap-add DAC_OVERRIDE --cap-add FOWNER --cap-add FSETID --cap-add KILL --cap-add SETGID --cap-add SETPCAP --cap-add SETUID --cap-add SYS_BOOT --security-opt label=type:container_runtime_t --tmpfs /var/lib/journal --stop-signal SIGRTMIN+3 --mount type=bind,source=/sys/fs/cgroup,target=/sys/fs/cgroup,readonly --tmpfs /run:exec --tmpfs /run/lock --tmpfs /tmp --mount type=bind,source=/home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share,target=/x11docker --mount type=bind,source=/home/werner/.local/share/x11docker/hongyizhao-deepin-wine,target=/home/werner --mount type=bind,source=/home/werner,target=//home.host/werner --mount type=bind,source=/home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/pulseaudio.client.conf,target=/etc/pulse/client.conf,readonly --workdir /tmp --entrypoint env --env container=docker --env XAUTHORITY=/x11docker/Xauthority.client --env DISPLAY=192.168.10.100:119 --env PULSE_COOKIE=/x11docker/pulseaudio.cookie --env PULSE_SERVER=unix:/x11docker/pulseaudio.socket --env HOME=/home/werner --env USER=werner --device /dev/mem:/dev/mem --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot /bin/sh - /x11docker/containerrootrc
956182 tail --pid=945122 -n +1 -f /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/stderr
956188 tail --pid=945122 -n +1 -f /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/stdout
958730 /bin/sh -c /bin/journalctl --follow --no-tail >> /x11docker/systemd.journal.log 2>&1
958732 /bin/sh -c while sleep 1; do systemctl is-active console-getty >/dev/null || { echo timetosaygoodbye >>/x11docker/timetosaygoodbye ; systemctl halt ; } ; [ -s /x11docker/timetosaygoodbye ] && systemctl halt ; done
964786 sh /x11docker/cmdrc
964874 tail -f /x11docker/stdout
964875 tail -f /x11docker/stderr
```
 
> > Edit: --xpra fails along with --xoverip. Without this it works.
> 
> Is fixed now.

Great. I tried with the `-c --xpra` option, and it works smoothly.
 
> > What's the script and how to use it?
> 
> x11docker generates it internally. Depending on the display numbers etc. it looks like this:

I tried to use `--xephyr` without the `-c` option, but I still can't copy and paste text content between host and docker container.  

In short: Currently the only valid method is the `-c --xpra` option on my machine.

**Comment by mviereck** [comment]
> 953147 bash /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/clipboardrc

Somehow you have an instance of `clipboardrc` running. It is not started if you use `--nxagent -c`.

> I tried to use --xephyr without the -c option, but still can't copy and paste text content between host and docker container.

Without `-c` the clipboard is not shared.

Why at all do you use `--xoverip`?

**Comment by hongyi-zhao** [comment]
> > 953147 bash /home/werner/.cache/x11docker/89975920014-deepin-wine-apricot/share/clipboardrc
> 
> Somehow you have an instance of `clipboardrc` running. It is not started if you use `--nxagent -c`.

Let me debug it as follows:

With the `--xephyr -c` option:

```shell
$ pgrep -af clipboardrc
3209961 bash /home/werner/.cache/x11docker/91877410815-deepin-wine-apricot/share/clipboardrc
```
With the `--nxagent -c` option:

```shell
$ pgrep -af clipboardrc
3726861 bash /home/werner/.cache/x11docker/92319116602-deepin-wine-apricot/share/clipboardrc
```

With the `--xpra -c` option:
 
```shell
$ pgrep -af clipboardrc
$ 
```

> > I tried to use --xephyr without the -c option, but still can't copy and paste text content between host and docker container.
> 
> Without `-c` the clipboard is not shared.

With it, the problem reported here will be triggered.
 
> Why at all do you use `--xoverip`?

See [here](https://github.com/mviereck/dockerfile-x11docker-deepin/issues/36#issuecomment-735017143).

**Comment by mviereck** [comment]
Is `nxagent` installed at all on your host? Otherwise x11docker will fall back to use `--xephyr`.
Use `--fallback=no` to disable fallbacks. Than x11docker will fail if `--nxagent` is not possible.

**Comment by hongyi-zhao** [comment]
Thank you for your insightful and accurate analysis. It turns out that `nxagent` hasn't been installed yet, and I installed it with the following command:
 
`$ sudo apt install nxagent`

Now, the following option also works:

`--nxagent -c --fallback=no`

And I also confirm that the `clipboardrc` process disappears:

```shell
$ pgrep -af clipboardrc
$ 
```

**Comment by mviereck** [comment]
> But it seems that [nxagent](https://github.com/ArcticaProject/nx-libs/) doesn't support comp image from host to docker container, while [xpra](https://github.com/Xpra-org/xpra) does.

Yes, image clipboard transfer only works with xpra.

**Comment by hongyi-zhao** [comment]
Another strange behavior: when using [xpra](https://github.com/Xpra-org/xpra), the image capture by [shutter](https://github.com/shutter-project/shutter) can be copied from host to container, while the one captured by [ksnip](https://github.com/ksnip/ksnip) cannot..

**Comment by mviereck** [comment]
> Another strange behavior: when using [xpra](https://github.com/Xpra-org/xpra), the image captured by [shutter](https://github.com/shutter-project/shutter) can be copied from host to container, while the one captured by [ksnip](https://github.com/ksnip/ksnip) cannot.

The entire X11 clipboard thing in general is a mess. It is hard to debug odd behaviour.

**Comment by mviereck** [comment]
>> Why at all do you use --xoverip?

> See https://github.com/mviereck/dockerfile-x11docker-deepin/issues/36#issuecomment-735017143.

I just checked, it seems `--xoverip` is not needed anymore. I could run `sudo xterm` without `--xoverip`.
Maybe that was a bug in `sudo` that is fixed meanwhile.

> --share /dev/mem

Why do you use this? I'd discourage it.

**Comment by hongyi-zhao** [comment]
> With `--xpra` you can also use the `--scale` option if that is of interest for you.

This option seems rather complicated:

```
$ x11docker -h | egrep -A4 -- '^[ ]*--scale'
     --scale=N         Scale/zoom factor N for xpra, Xorg or Weston.
                       Allowed for --xpra, --xorg --xpra-xwayland: 0.25...8.0.
                       Allowed for --weston and --weston-xwayland: 1...9.
                       (Mismatching font sizes can be adjusted with --dpi).
                       Odd resolutions with --xorg might need --scale=1.
```
Would you please give me an example usage, especially with `--dpi`?

**Comment by mviereck** [comment]
> This option seems rather complicated:

I might need to ease the description. In fact it is simple.
For xpra only this line is of interest:
>                        Allowed for --xpra, --xorg --xpra-xwayland: 0.25...8.0.

Try a value between 0.25 an 8.
For example `--scale=0.5` or `--scale=2`.

I'll just remove the `--dpi` line.

**Comment by hongyi-zhao** [comment]
> Try a value between 0.25 an 8. For example `--scale=0.5` or `--scale=2`.

I tried some values, but it seems that only the default scale factor 1 gives the most pleasing and satisfying effect.

**Comment by hongyi-zhao** [comment]
> I just checked, it seems `--xoverip` is not needed anymore. I could run `sudo xterm` without `--xoverip`. Maybe that was a bug in `sudo` that is fixed meanwhile.

Yes. I confirmed your conclusion.
 
> > --share /dev/mem
> 
> Why do you use this? I'd discourage it.

See https://github.com/mviereck/dockerfile-x11docker-deepin/issues/46.

**Comment by mviereck** [comment]
> See https://github.com/mviereck/dockerfile-x11docker-deepin/issues/46.

Oh, I see. But if you don't need `dmidecode` regulary, I'd remove `--share /dev/mem` for security reasons. According to the SO ticket you would also need `--cap-add SYS_RAWIO` that I would discourage, too.

**Comment by hongyi-zhao** [comment]
> But if you don't need `dmidecode` regulary, I'd remove `--share /dev/mem` for security reasons. 

I see. For the sake of debugging, I want to keep it.

> According to the SO ticket

BTW, what do you mean by saying `SO ticket`?

> you would also need `--cap-add SYS_RAWIO` that I would discourage, too.

Thank you for your reminder. I've added this option.

**Comment by mviereck** [comment]
> BTW, what do you mean by saying SO ticket?

You have referred to stack overflow: https://stackoverflow.com/questions/54068234/cant-run-dmidecode-on-docker-container
With SO I mean stack overflow.

**Comment by hongyi-zhao** [comment]
In https://github.com/mviereck/x11docker/issues/428#issuecomment-1086821922, you said:

> With `--xephyr` x11docker uses a custom script.

Do you mean only when using `-c` with `--xephyr`, the custom script will be automatically generated and take effect?

**Comment by mviereck** [comment]
> Do you mean only when using -c with --xephyr, the custom script will be automatically generated and take effect?

The clipboard script is used with `--xephyr`, `--weston-xwayland` and `--xorg`.

**Comment by hongyi-zhao** [comment]
Let me try to further clarify my confusion as follows:

1. `--xephyr`, `--weston-xwayland` and `--xorg` don't have their own clipboard manager.
2. This clipboard script must be activated by the `-c` option.
3. As a result, when using `-c` with `--xephyr`, `--weston-xwayland`, or `--xorg`, this clipboard script will take effect.

**Comment by mviereck** [comment]
Yes, correct.

**Comment by mviereck** [comment]
I have adjusted the clipboard script a bit. It should not disturb image clips anymore.

**Comment by mviereck** [comment]
I have included some basic graphical clips support in the clipboard script.
I was able to run knsip in a container using `--xephyr -c` and to copy some graphics to the host clipboard.

**Comment by hongyi-zhao** [comment]
In https://github.com/mviereck/x11docker/issues/428#issuecomment-1086884021:
> I'll just remove the `--dpi` line.

Why do you plan to do this? I just want to know how to set the resolution of docker container to achieve the best, at least close to or the same as the host. Is this possible?

**Comment by mviereck** [comment]
I have only removed the `--dpi` explanation from the `--scale` option to avoid confusion.
x11docker always tries to automatically set the same dpi for the container as on host.
The dpi value is regarded by some but not all applications. At most it influences font sizes.
You can just try out `--dpi` to see the results. Try e.g. `--dpi=70` or `--dpi=100`.

**Comment by hongyi-zhao** [comment]
I think that it should be automatically set according to the result of the following command:
```shell
$ xrdb -query | grep dpi
Xft.dpi:	96
$ xdpyinfo | grep -E 'dimensions|resolution'
  dimensions:    1920x1080 pixels (508x285 millimeters)
  resolution:    96x96 dots per inch
```
In this case, on my machine, it should be set as follows accordingly:

`--dpi=70`

**Comment by mviereck** [comment]
x11docker uses `xdpyinfo` to get the dpi setting from host.
In your case it would set `--dpi=96`. 
You can check that in the `--debug` output where the generated X server command is shown. There should be a line `-dpi 96`.

**Comment by hongyi-zhao** [comment]
> You can check that in the `--debug` output where the generated X server command is shown. There should be a line `-dpi 96`.

Yes. See below:

![image](https://user-images.githubusercontent.com/11155854/161498528-c2688dd2-dc02-4c01-bbd2-8a9031cfa5ee.png)

**Comment by mviereck** [comment]
I've added support for middle mouse click selection.
This was a hard one, I had to rewrite the clipboard code from scratch. It took several hours for these few lines. `xclip` can be itchy.
However, finally it is done. Since a long time I had the wish to improve the x11docker clipboard management.
Graphical clips are implemented rudimentary only, but should work for most use cases.
Nice: It works well with and without the Xfce4 clipboard manager.

**Comment by hongyi-zhao** [comment]
> `xclip` can be itchy.

What do you mean by saying this?

BTW: Based on test, I can only copy the image from docker to host.

**Comment by mviereck** [comment]
> NB: Based on test, I can only copy the image from docker to host.

How did you test?
I've tried with `knsip` in container and it works.

> What do you mean by saying this?

Try to write scripts with it and you'll see. :-)
A very odd thing: If I run `xclip` in a function, I cannot return to the main script.

**Comment by hongyi-zhao** [comment]
> How did you test?

Sorry for my fuzzy description. In fact, there are so many ways to do the test mentioned here, and I original statement is not accurate. In order to have a systematic understanding of this problem, I tried the following tests:

(A). Start docker container with `--xephyr -c --fallback=no` via `x11docker`, then confirm the following:

Success: 
1. Run `flameshot` in container to capture some screenshot and then copy and paste it onto GitHub.
2. Run `ksnip` or `shutter` on host to capture some screenshot and then copy and paste it into the `gimp` running in docker container.

Failure: Run `ksnip` or `shutter` on host to capture some screenshot and then copy and paste it into the `wechat` running in docker container.

(B). Start docker container with `--xephyr -c --fallback=no` via `x11docker`, then confirm the following:

All of the above tests were successful.

> If I run `xclip` in a function, I cannot return to the main script.

Can you demonstrate this to me with a minimal bash script?

**Comment by mviereck** [comment]
> Failure: Run ksnip or shutter on host to capture some screenshot and then copy and paste it into the wechat running in docker container.

> All of the above tests were successful.

Does it work in `wechat` now?
If not, providing a clipboard manager in the container might help. 
`xclip` can provide only one image format at a time. Clipboard managers like `xfce4-clipman` can provide the clipped image in multiple formats.

**Comment by hongyi-zhao** [comment]
> Does it work in `wechat` now?

This only works for `xpra -c --fallback=no` when copying and pasting images from the host to `WeChat` running in the container.

> Clipboard managers like `xfce4-clipman` can provide the clipped image in multiple formats.

Do you mean install it into the docker container as follows?

`$ sudo apt install xfce4-clipman`

> #! /bin/bash
> myclip() {
>   xclip -selection clipbord -in <<< "hello world"
>   echo x
>   return
> }
> set -x
> while true; do
>   y="$(myclip)"
> done

It will be blocked there forever:

![image](https://user-images.githubusercontent.com/11155854/161712904-990d841b-b333-412e-893c-62f75f238199.png)

**Comment by mviereck** [comment]
> Do you mean install it into the docker container as follows?

Installing in image and also starting in container. E.g. with `--runasuser 'xfce4-clipman &'`. Or, in deepin, add it to the desktop autostart. Maybe a deepin clipboard manager exists, too, I don't know.

> It will be blocked there forever:

It is not blocked if it is called without $():
```
#! /bin/bash
myclip() {
  xclip -selection clipbord -in <<< "hello world"
  echo x
  return
}
set -x
while true; do
  myclip
done
```
Note that xclip forkes itself into background and keeps running to actively provide the clip. However, this should not block the function from returning.

**Comment by hongyi-zhao** [comment]
Maybe the `xclip` developers can give some hints.

**Comment by hongyi-zhao** [comment]
How to substitute `xfce4-clipman` for `xclip` as the default both on host and in container?

**Comment by mviereck** [comment]
It should not be substituted but run aside and independent from x11docker.
However, meanwhile I tried xfce4-clipman in container and it crashes after a while. Within a desktop environment like deepin it might work.

**Comment by mviereck** [comment]
Nevermind, neither xfce4-clipman nor some other clipboard managers seems to do any conversion on their own.

**Comment by mviereck** [comment]
I found a working clipboard manager!
The problem is that `xclip` can only provide one image format at a time.
`copyq` is a clipboardmanager that takes the image from `xclip` and provides it to other clients in multiple image formats.

To try out directly:
 - Install `copyq`
 - run x11docker with `--clipboard --runfromhost 'copyq &'`
 
Likely wechat will succeed to paste images from the clipboard.

**Comment by hongyi-zhao** [comment]
> Sorry, I've checked wrong.

What do you mean by saying this?

**Comment by hongyi-zhao** [comment]
1. This can start docker container:

```bash
$ x11docker --runasroot 'sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers
        |#$ sudo grep -Ev '\''^[ ]*(#|$)'\'' /etc/sudoers  
        |Defaults	env_reset
        |Defaults	mail_badpass
        |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
        |root	ALL=(ALL:ALL) ALL
        |%admin ALL=(ALL) ALL
        |%sudo	ALL=(ALL:ALL) ALL
        |$USER ALL=(ALL) NOPASSWD:ALL
	EOF' --debug --xephyr -c --fallback=no --runfromhost 'copyq &' --network=bridge --pulseaudio --home --share=$HOME --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add SYS_RAWIO --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot	
```

3. This will fail:

```bash
$ xephyr="--xephyr -c --fallback=no --runfromhost 'copyq &'"

$ x11docker --runasroot 'sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers
        |#$ sudo grep -Ev '\''^[ ]*(#|$)'\'' /etc/sudoers  
        |Defaultsenv_reset
        |Defaultsmail_badpass
        |Defaultssecure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
        |rootlesskitALL=(ALL:ALL) ALL
        |%admin ALL=(ALL) ALL
        |%sudoALL=(ALL:ALL) ALL
        |$USER ALL=(ALL) NOPASSWD:ALL
EOF' --debug $xephyr --network=bridge --pulseaudio --home --share=$HOME --sudouser --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add SYS_RAWIO --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot
DEBUGNOTE[16:31:09,335]: Detected cgroup v1
DEBUGNOTE[16:31:09,817]: check_host(): ps can watch root processes: yes
DEBUGNOTE[16:31:09,894]: host user: werner 1000:1000 /home/werner
x11docker WARNING: User werner is member of group docker.
  That allows unprivileged processes on host to gain root privileges.

DEBUGNOTE[16:31:10,145]: storeinfo(): cache=/home/werner/.cache/x11docker/33868571032-
DEBUGNOTE[16:31:10,161]: storeinfo(): stdout=/home/werner/.cache/x11docker/33868571032-/share/stdout
DEBUGNOTE[16:31:10,176]: storeinfo(): stderr=/home/werner/.cache/x11docker/33868571032-/share/stderr
DEBUGNOTE[16:31:10,223]: waitforlogentry(): tailstderr: Waiting for logentry "x11docker=ready" in store.info
DEBUGNOTE[16:31:10,223]: waitforlogentry(): tailstdout: Waiting for logentry "x11docker=ready" in store.info
DEBUGNOTE[16:31:10,432]: Default runtime: runc
DEBUGNOTE[16:31:10,509]: storeinfo(): containeruser=werner
DEBUGNOTE[16:31:10,525]: container user: werner 1000:1000 /home/werner
x11docker WARNING: You are running GNOME desktop in outdated version
  GNOME Shell 3.36.9
  This might cause issues with host applications if using additional X servers.
  It is recommended to use another desktop environment or GNOME >= 3.38.
  Only --xorg or discouraged option --hostdisplay might work as expected.

DEBUGNOTE[16:31:10,655]: Dependency check for --xephyr: 0
DEBUGNOTE[16:31:10,664]: Dependencies of --xephyr already checked: 0 
DEBUGNOTE[16:31:10,671]: Dependencies of --xephyr already checked: 0 
DEBUGNOTE[16:31:10,678]: Dependencies of --xephyr already checked: 0 
DEBUGNOTE[16:31:10,686]: Dependencies of --xephyr already checked: 0 
DEBUGNOTE[16:31:10,693]: storeinfo(): xserver=--xephyr
x11docker WARNING: Option --network: Container has access to
  local network and internet.

DEBUGNOTE[16:31:10,774]: storepid(): Stored pid '3999064' of 'watchpidlist': 3999064 pts/7    00:00:00 bash
DEBUGNOTE[16:31:10,820]: storepid(): Stored pid '3999142' of 'watchmessagefifo': 3999142 pts/7    00:00:00 bash
x11docker WARNING: Option --pulseaudio allows container applications
  to catch your audio output and microphone input.

DEBUGNOTE[16:31:11,416]: storeinfo(): pulseaudiomoduleid=43
DEBUGNOTE[16:31:11,529]: storeinfo(): DISPLAY=:117
DEBUGNOTE[16:31:11,549]: storeinfo(): XAUTHORITY=/home/werner/.cache/x11docker/33868571032-/share/Xauthority.client
DEBUGNOTE[16:31:11,562]: storeinfo(): XSOCKET=/tmp/.X11-unix/X117
DEBUGNOTE[16:31:11,580]: storeinfo(): XDG_RUNTIME_DIR=/run/user/1000
DEBUGNOTE[16:31:11,601]: storeinfo(): Xenv=DISPLAY=:117 XAUTHORITY=/home/werner/.cache/x11docker/33868571032-/share/Xauthority.client XSOCKET=/tmp/.X11-unix/X117 XDG_RUNTIME_DIR=/run/user/1000
DEBUGNOTE[16:31:11,650]: X server command:
  /usr/bin/Xephyr :117  \
  -retro \
  +extension RANDR \
  +extension RENDER \
  +extension GLX \
  +extension XVideo \
  +extension DOUBLE-BUFFER \
  +extension SECURITY \
  +extension DAMAGE \
  +extension X-Resource \
  -extension XINERAMA -xinerama \
  -extension MIT-SHM \
  +extension Composite +extension COMPOSITE \
  -extension XTEST -tst \
  -dpms \
  -s off \
  -auth /home/werner/.cache/x11docker/33868571032-/Xauthority.server \
  -nolisten tcp \
  -dpi 96 \
  -resizeable \
  -noxv \
  -screen 1824x984 \
  
DEBUGNOTE[16:31:11,658]: storeinfo(): x11dockerpid=3995513
DEBUGNOTE[16:31:11,724]: x11docker version:  7.1.5-beta-5
  Backend version:               Docker version 20.10.9, build c2ea9bc
  OCI Runtime:                   runc
  Host system:                   "Ubuntu 20.04.3 LTS"
  Host architecture:             amd64 (x86_64)
  Command:
    '/home/werner/Public/repo/github.com/mviereck/x11docker.git/x11docker' '--runasroot' 'sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers
        |#$ sudo grep -Ev '^[ ]*(#|$)' /etc/sudoers  
        |Defaultsenv_reset
        |Defaultsmail_badpass
        |Defaultssecure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
        |rootlesskitALL=(ALL:ALL) ALL
        |%admin ALL=(ALL) ALL
        |%sudoALL=(ALL:ALL) ALL
        |$USER ALL=(ALL) NOPASSWD:ALL
EOF' '--debug' '--xephyr' '-c' '--fallback=no' '--runfromhost' ''copyq' '&'' '--network=bridge' '--pulseaudio' '--home' '--share=/home/werner' '--sudouser' '--desktop' '--init=systemd' '--' '--device' '/dev/mem:/dev/mem' '--cap-add' 'SYS_RAWIO' '--cap-add=IPC_LOCK' '--cap-add=NET_RAW' '--cap-add=NET_BIND_SERVICE' '--' 'hongyizhao/deepin-wine:apricot' 
  Parsed options:
    
  ()  --runasroot 'sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers
        |#$ sudo grep -Ev '\''^[ ]*(#|$)'\'' /etc/sudoers  
        |Defaultsenv_reset
        |Defaultsmail_badpass
        |Defaultssecure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
        |rootlesskitALL=(ALL:ALL) ALL
        |%admin ALL=(ALL) ALL
        |%sudoALL=(ALL:ALL) ALL
        |$USER ALL=(ALL) NOPASSWD:ALL
EOF' --debug --xephyr -c --fallback 'no' --runfromhost ''\''copyq' --network 'bridge' --pulseaudio '' --home '' --share '/home/werner' --sudouser '' --desktop --init 'systemd' -- '&'\''' '--device' '/dev/mem:/dev/mem' '--cap-add' 'SYS_RAWIO' '--cap-add=IPC_LOCK' '--cap-add=NET_RAW' '--cap-add=NET_BIND_SERVICE' '--' 'hongyizhao/deepin-wine:apricot'
  x11docker was started by:      werner
  As host user serves:           werner
  Container user will be:        werner
  Container user password:       x11docker
  Running in a terminal:         yes
  Running on console:            no
  Running over SSH:              no
  Running sourced:               no
  bash $-:                       huBE
x11docker WARNING: Option --init=systemd slightly degrades container isolation.
  It adds some user switching capabilities x11docker would drop otherwise.
  However, they are still within default docker capabilities.
  Not within default docker capabilities it adds capability SYS_BOOT.
  Some processes in container will run as root.

x11docker WARNING: Option --init=systemd: Sharing /sys/fs/cgroup from host.


x11docker ERROR: Image &' not found locally.
  Please pull or build image first.

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: /home/werner/.cache/x11docker/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker

DEBUGNOTE[16:31:11,817]: time to say goodbye (error)
DEBUGNOTE[16:31:11,827]: storeinfo(): error=64
DEBUGNOTE[16:31:11,841]: Terminating x11docker.
DEBUGNOTE[16:31:11,848]: time to say goodbye (finish)
DEBUGNOTE[16:31:11,909]: finish(): Checking pid 3999142 (watchmessagefifo): 3999142 pts/7    00:00:00 bash
DEBUGNOTE[16:31:11,974]: finish(): Checking pid 3999064 (watchpidlist): 3999064 pts/7    00:00:00 bash
DEBUGNOTE[16:31:12,026]: termpid(): Terminating 3999064 (watchpidlist): 3999064 pts/7    00:00:00 bash
DEBUGNOTE[16:31:12,209]: termpid(): Terminating 3999142 (watchmessagefifo): 3999142 pts/7    00:00:00 bash
DEBUGNOTE[16:31:12,271]: waitforlogentry(): tailstderr: Stopped waiting for x11docker=ready in store.info due to terminating signal.
DEBUGNOTE[16:31:12,278]: waitforlogentry(): tailstdout: Stopped waiting for x11docker=ready in store.info due to terminating signal.
DEBUGNOTE[16:31:12,341]: x11docker exit code: 64

```

**Comment by mviereck** [comment]
I have implemented a working solution that needs image `x11docker/xserver`. If you already have this image, please pull it again.

The image now contains `copyq` and uses it to provide multiple image formats after `xclip` has send an image clip.

For your setup, just pull image `x11docker/xserver` and run:
```
x11docker --xephyr --desktop --clipboard --init=systemd -- hongyizhao/deepin-wine:apricot
```
wechat should be able to paste images now.

> $ xephyr="--xephyr -c --fallback=no --runfromhost 'copyq &'"

This will be parsed wrong. bash won't recognize that '' within "" should be seen as a single argument.

**Comment by hongyi-zhao** [comment]
> x11docker --xephyr --desktop --clipboard --init=systemd -- hongyizhao/deepin-wine:apricot

These options can't enable internet access:

![image](https://user-images.githubusercontent.com/11155854/161936174-6f621d08-3f5d-44bc-bf8f-d807d1a55e3d.png)

Then I tried with my original xephyr related options without `--runfromhost 'copyq &'`, still I can't copy image from host and paste in into WeChat.

> > $ xephyr="--xephyr -c --fallback=no --runfromhost 'copyq &'"
> 
> This will be parsed wrong. bash won't recognize that '' within "" should be seen as a single argument.

So, how can I put these options into a variable to facilitate debugging?

**Comment by mviereck** [comment]
> Then I tried with my original xephyr related options without --runfromhost 'copy &', still I can't copy image from host and paste it into WeChat.

Did you pull image `x11docker/xserver`?

> So, how can I put these options into a variable to facilitate debugging?

It is not possible. Maybe  `--runfromhost copy\ &` would work.
However, you don't need  `--runfromhost 'copy &'` anymore.

**Comment by hongyi-zhao** [comment]
> Did you pull image `x11docker/xserver`?

```bash
$ docker images|grep xserver
x11docker/xserver           latest    360fa88946c0   2 hours ago         936MB
```

> You also need to update x11docker.

```bash
$ git log -1
commit f5e4c6cef2fac78cc73415421ecf11dad8dafaed (HEAD -> master, origin/master, origin/HEAD)
Author: mviereck <bachbaum24@gmx.de>
Date:   Wed Apr 6 10:29:08 2022 +0200

    --xc --clipboard: Use copyq to provide multiple clip TARGETS formats #428
```

**Comment by mviereck** [comment]
Ok. Than I don't know what wechat might missing here.
If you have `xclip` in you deepin image, you could check `xclip -selection clipboard -out -t TARGETS`.
It should look like:
```
$ xclip -selection clipboard -out -t TARGETS
image/png
application/x-copyq-owner
application/x-qt-image
image/bmp
image/cur
image/ico
image/jpeg
image/jpg
image/pbm
BITMAP
image/pgm
image/ppm
PIXMAP
image/xbm
image/xpm
TARGETS
MULTIPLE
TIMESTAMP
SAVE_TARGETS
```
If wechat cannot read any of the provided image formats, than i don't know wat could be done.
With xclip alone only `image/png` was available.

**Comment by hongyi-zhao** [comment]
> If you have `xclip` in you deepin image, you could check `xclip -selection clipboard -out -t TARGETS`.
> It should look like:

See my following testing results.

On host:
```bash
$ git log -1
commit 152499c437f6e0ab2a7d021b4504a4a676fa9968 (HEAD -> master, origin/master, origin/HEAD)
Author: mviereck <bachbaum24@gmx.de>
Date:   Wed Apr 6 13:18:55 2022 +0200

    --xc --clipboard: use copyq only for selection clipboard #428

$ pgrep -af copyq
17627 /usr/bin/copyq
20344 /usr/bin/copyq --clipboard-access monitorClipboard
20520 /usr/bin/copyq eval -- runMenuCommandFilters()
954863 copyq
955280 /usr/bin/copyq --clipboard-access monitorClipboard
955292 /usr/bin/copyq eval -- runMenuCommandFilters()
1018430 /usr/bin/copyq --clipboard-access synchronizeFromSelection

$ pgrep -ax docker
954215 docker exec x11docker_X122_xserver_49375858020 env WAYLAND_DISPLAY= xinit /home/werner/.cache/x11docker/49375858020-deepin-wine-apricot/share/xinitrc -- /usr/bin/Xephyr :122 -retro +extension RANDR +extension RENDER +extension GLX +extension XVideo +extension DOUBLE-BUFFER +extension SECURITY +extension DAMAGE +extension X-Resource -extension XINERAMA -xinerama +extension MIT-SHM +extension Composite +extension COMPOSITE -extension XTEST -tst -dpms -s off -auth /home/werner/.cache/x11docker/49375858020-deepin-wine-apricot/Xauthority.server -nolisten tcp -dpi 96 -resizeable -noxv -screen 1824x984
955392 /usr/bin/docker run --pull never --rm --tty --name x11docker_X122_hongyizhao-deepin-wine-apricot_49375858020 --user root --userns=host --runtime=runc --network bridge --cap-drop ALL --cap-add AUDIT_WRITE --cap-add CHOWN --cap-add DAC_OVERRIDE --cap-add FOWNER --cap-add FSETID --cap-add KILL --cap-add SETGID --cap-add SETPCAP --cap-add SETUID --cap-add SYS_BOOT --security-opt label=type:container_runtime_t --tmpfs /var/lib/journal --stop-signal SIGRTMIN+3 --mount type=bind,source=/sys/fs/cgroup,target=/sys/fs/cgroup,readonly --tmpfs /run:exec --tmpfs /run/lock --tmpfs /tmp --mount type=bind,source=/home/werner/.cache/x11docker/49375858020-deepin-wine-apricot/share,target=/x11docker --mount type=bind,source=/home/werner/.local/share/x11docker/hongyizhao-deepin-wine,target=/home/werner --mount type=bind,source=/home/werner,target=//home.host/werner --mount type=bind,source=/home/werner/.cache/x11docker/49375858020-deepin-wine-apricot/tmp/.X11-unix/X122,target=/tmp/.X11-unix/X122,readonly --ipc=container:x11docker_X122_xserver_49375858020 --mount type=bind,source=/home/werner/.cache/x11docker/49375858020-deepin-wine-apricot/pulseaudio.client.conf,target=/etc/pulse/client.conf,readonly --workdir /tmp --entrypoint env --env container=docker --env XAUTHORITY=/x11docker/Xauthority.client --env DISPLAY=:122 --env PULSE_COOKIE=/x11docker/pulseaudio.cookie --env PULSE_SERVER=unix:/x11docker/pulseaudio.socket --env HOME=/home/werner --env USER=werner --device /dev/mem:/dev/mem --cap-add SYS_RAWIO --cap-add=IPC_LOCK --cap-add=NET_RAW --cap-add=NET_BIND_SERVICE -- hongyizhao/deepin-wine:apricot /bin/sh - /x11docker/containerrootrc
```

In container:
```bash
$ xclip -selection clipboard -out -t TARGETS
text/plain
UTF8_STRING
STRING
TEXT
application/x-copyq-owner
TARGETS
MULTIPLE
TIMESTAMP
SAVE_TARGETS
```

**Comment by hongyi-zhao** [comment]
> To have the same output as in my example you need an image in the clipboard.

Do you mean to copy an image to the copyq's clipboard running in `x11docker/xserver`?

**Comment by mviereck** [comment]
Just copy an image on your host or in your deepin container.
`x11docker/xserver` is used internally, you don't need to do anything with it.

**Comment by hongyi-zhao** [comment]
> Just copy an image on your host or in your deepin container.

I retested and confirmed that both methods can paste the image into wechat.

**Comment by hongyi-zhao** [comment]
As far as copying the image from shutter running on host into the docker container, I find a very strange thing as described below: I must first open another arbitrary image with GNOME image viewer and do the copy operation.

The working steps are as follows:

1. Open another arbitrary image with GNOME image viewer and do the copy operation.
2. Copy the image from shutter running on host into the docker container.
3. After I finished 1, the subsequent steps no longer need to run it.

**Comment by mviereck** [comment]
> As far as copying the image from shutter running on host into the docker container, I find a very strange thing as described below: I must first open another arbitrary image with GNOME image viewer and do the copy operation.

If the issue is specific to shutter, but the issue does not happen with other like knsip, than it is likely a shutter issue and has nothing to do with x11docker.

> Another question: If the [x11docker/xserver](https://github.com/mviereck/dockerfile-x11docker-xserver) is used, there is needless to use the nxagent or xpra. Am I right?

You would not need to install them on host. They are already provided by the image.
It still makes sense to provide `xpra` on host, too, because there are new options `--xpra2` and `--xpra2-xwayland` that provide the most performant xpra setup using xpra on host as well as in container. Compare #257

**Comment by hongyi-zhao** [comment]
> If the issue is specific to shutter, but the issue does not happen with other like knsip, than it is likely a shutter issue and has nothing to do with x11docker.


I further checked this issue, and found that both shutter and ksnip have the similar behavior: I must continuously perform the following two operations for the first time to use them.

ksnip:

![image](https://user-images.githubusercontent.com/11155854/162203010-0a87b3fa-d224-4963-8f05-e7c739b46151.png)

shutter:

![image](https://user-images.githubusercontent.com/11155854/162202905-2bb1919a-2e39-4de3-9e1c-202313d790d3.png)

> It still makes sense to provide `xpra` on host, too, because there are new options `--xpra2` and `--xpra2-xwayland` that provide the most performant xpra setup using xpra on host as well as in container.

1. What's the criteria by saying "the most performant"?
2. Must xpra be installed both on host and in container?

**Comment by hongyi-zhao** [comment]
> Here i only need one clip operation, and it works.

Do you mean the second operation marked by me?

> Maybe the data url copy fails in general.

What do you mean exactly?

**Comment by mviereck** [comment]
> Do you mean the second operation marked by me?

Yes. That is a real image copy.

> What do you mean exactly?

At (1) you one time marked "Copy as data URI". That is not a real image format. At the other (1) you copy a file name. That is not an image format, too.

**Comment by hongyi-zhao** [comment]
But if I only do the step (2) for each, it doesn't work: the image can't be pasted into the container.

**Comment by mviereck** [comment]
I cannot reproduce your issue. It just works here.
Check the output of `xclip -selection clipboard -out -t TARGETS` if you see image formats after an image copy on host.

**Comment by hongyi-zhao** [comment]
After waiting for a sufficient time (a few seconds to one minute), I can still observe the question I report here. BTW, I have both `copyq` and `parcellite` running on my machine, as shown below:

```bash
$ pgrep -ax parcellite 
12869 parcellite
$ pgrep -ax copyq 
12916 /usr/bin/copyq
15688 /usr/bin/copyq --clipboard-access monitorClipboard
15846 /usr/bin/copyq eval -- runMenuCommandFilters()
467944 copyq
468344 /usr/bin/copyq --clipboard-access monitorClipboard
468355 /usr/bin/copyq eval -- runMenuCommandFilters()
620936 /usr/bin/copyq --clipboard-access synchronizeToSelection
```
I don't know if this will affect or interfere with the above issue.

**Comment by mviereck** [comment]
> I don't know if this will affect or interfere with the above issue.

That is possible. More than one clipboard manager at a time on the host might cause issues.

**Comment by hongyi-zhao** [comment]
> That is possible. More than one clipboard manager at a time on the host might cause issues.

Really. After I kill `parcellite`, `x11docker --xephyr --clipboard [...]` works as expected.

> Here I use `xfce4-clipman` as clipboard manager on host. `x11docker --clipboard [...]` works well with and without it.

Do you mean with or without `xfce4-clipman`?

BTW, I noticed another very strange thing on my machine: For gedit, middle click paste only work for stuff copied outside gedit. More specifically, if I select some text in gedit itself, then middle click in the same file opened by gedit doesn't paste the corresponding content at all, but the cotent still can be middle-click pasted into other files opened by gedit.

**Comment by mviereck** [comment]
> Do you mean with or without xfce4-clipman?

It works well in both cases.

> Do you mean with or without xfce4-clipman?

I cannot reproduce that. It works well here.

**Comment by mviereck** [comment]
I occasionally had issues with the clipboard. It seems that they are caused by the call of `copyq` in x11docker.
That might explain your `gedit` issues, too.
I've disabled the `copyq` code in x11docker. So there will be one image format only in case of image clips.

**Comment by hongyi-zhao** [comment]
This will disable image copying and pasting between the host and wechat running in the container.

**Comment by mviereck** [comment]
> This will disable image copying and pasting between the host and wechat running in the container.

Did you already check this before reporting?
Previously that issue was at first place caused by multiple clipboard managers running on your host.

**Comment by hongyi-zhao** [comment]
I tried with and without multiple clipboard managers running on the host, but meet the same problem.

**Comment by mviereck** [comment]
Because disabling the copyq code fixed more important issues, I won't reenable it for wechat alone.
You could ask at wechat to support `image/png` clips.

Or you could install and run CopyQ in your deepin image and run `copyq select 0` manually before pasting into wechat. Selecting the clip in the CopyQ dialog works as well. It just does not work automatically. Compare https://github.com/hluk/CopyQ/issues/1960

**Comment by hongyi-zhao** [comment]
Really, it works exactly as you described above.
